---
sidebar: sidebar 
permalink: reference-limits-azure.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, page blobs, ebs, managed disks 
summary: O Cloud Volumes ONTAP tem limites de configuração de storage no Azure para fornecer operações confiáveis. Para obter o melhor desempenho, não configure o sistema com os valores máximos. 
---
= Limites de armazenamento no Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O Cloud Volumes ONTAP tem limites de configuração de storage para fornecer operações confiáveis. Para obter o melhor desempenho, não configure o sistema com os valores máximos.



== Capacidade máxima do sistema por licença

A capacidade máxima do sistema para um sistema Cloud Volumes ONTAP é determinada pela sua licença. A capacidade máxima do sistema inclui storage baseado em disco e storage de objetos usado para categorização de dados.

O NetApp não suporta exceder o limite de capacidade do sistema. Se você atingir o limite de capacidade licenciado, o BlueXP  exibirá uma mensagem de ação necessária e não permitirá mais adicionar discos adicionais.

[cols="25,75"]
|===
| Licença | Capacidade máxima do sistema (discos e armazenamento de objetos) 


| Freemium | 500 GiB 


| PAYGO Explore | 2 TIB (disposição de dados em categorias não é compatível com o Explore) 


| Padrão PAYGO | 10 TIB 


| PAYGO Premium | 368 TIB 


| Licença baseada em nó | 2 PIB (requer várias licenças) 


| Licença baseada em capacidade | 2 PIB 
|===
.No caso de HA, o limite de capacidade da licença por nó ou para todo o par de HA?
O limite de capacidade aplica-se a todo o par de HA. Não é por nó. Por exemplo, se você usar a licença Premium, poderá ter até 368 TIB de capacidade entre os dois nós.



== Limites de disco e disposição em camadas por tamanho da VM

Os limites de disco abaixo são específicos para discos que contêm dados de usuário. Os limites não incluem o disco raiz, o disco central e a VNVRAM.

As tabelas abaixo mostram a capacidade máxima do sistema por tamanho da VM somente com discos e com a disposição em camadas de discos e dados inativos no storage de objetos.

* Os sistemas de nó único podem usar discos gerenciados HDD padrão, discos gerenciados SSD padrão e discos gerenciados SSD premium, com até 32 TIB por disco. O número de discos suportados varia de acordo com o tamanho da VM.
* Os SISTEMAS HA usam blobs de página Premium como discos, com até 8 TIB por blob de página. O número de discos suportados varia de acordo com o tamanho da VM.



NOTE: Você pode comprar várias licenças baseadas em nós para um sistema de nó único ou par de HA da Cloud Volumes ONTAP BYOL para alocar mais de 368 TIB de capacidade, até o limite máximo de capacidade do sistema testado e suportado de 2 PIB. Esteja ciente de que os limites de disco podem impedir que você alcance o limite de capacidade usando discos sozinhos. Você pode ir além do limite de disco pelo https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["disposição em camadas dos dados inativos no storage de objetos"^]. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html["Saiba como adicionar licenças de sistema adicionais ao Cloud Volumes ONTAP"^]. Embora o Cloud Volumes ONTAP suporte até a capacidade máxima do sistema testada e suportada de 2 PIB, cruzar o limite de 2 PIB resulta em uma configuração de sistema não suportada.



=== Nó único com licença Premium

[cols="14,20,31,33"]
|===
| Tamanho da VM | Discos MAX Data por nó | Capacidade máxima do sistema somente com discos | Capacidade máxima do sistema com discos e categorização de dados 


| DS5_v2 | 61 | 368 TIB | 368 TIB 


| DS14_v2 | 61 | 368 TIB | 368 TIB 


| DS15_v2 | 61 | 368 TIB | 368 TIB 


| E32s_v3 | 29 | 368 TIB | 368 TIB 


| E48s_v3 | 29 | 368 TIB | 368 TIB 


| E64is_v3 | 29 | 368 TIB | 368 TIB 


| E80ids_v4 | 61 | 368 TIB | 368 TIB 
|===


=== Nó único com licenciamento baseado em nó

[cols="10,18,18,18,18,18"]
|===
| Tamanho da VM | Discos MAX Data por nó 2+| Capacidade máxima do sistema com uma licença 2+| Capacidade máxima do sistema com várias licenças 


2+|  | *Discos sozinhos* | *Discos e categorização de dados* | *Discos sozinhos* | *Discos e categorização de dados* 


| DS4_v2 | 29 | 368 TIB | 368 TIB | 896 TIB | 2 PIB 


| DS5_v2 | 61 | 368 TIB | 368 TIB | 896 TIB | 2 PIB 


| DS13_v2 | 29 | 368 TIB | 368 TIB | 896 TIB | 2 PIB 


| DS14_v2 | 61 | 368 TIB | 368 TIB | 896 TIB | 2 PIB 


| DS15_v2 | 61 | 368 TIB | 368 TIB | 896 TIB | 2 PIB 


| E4s_v3 | 5 | 160 TIB | 368 TIB | 160 TIB | 2 PIB 


| E8s_v3 | 13 | 368 TIB | 368 TIB | 416 TIB | 2 PIB 


| E32s_v3 | 29 | 368 TIB | 368 TIB | 896 TIB | 2 PIB 


| E48s_v3 | 29 | 368 TIB | 368 TIB | 896 TIB | 2 PIB 


| E64is_v3 | 29 | 368 TIB | 368 TIB | 896 TIB | 2 PIB 


| L8s_v2 | 13 | 368 TIB | 368 TIB | 416 TIB | 2 PIB 


| E80ids_v4 | 61 | 368 TIB | 368 TIB | 896 TIB | 2 PIB 
|===


=== Nó único com licenciamento baseado em capacidade

[cols="14,20,31,33"]
|===
| Tamanho da VM | Discos MAX Data por nó | Capacidade máxima do sistema somente com discos | Capacidade máxima do sistema com discos e categorização de dados 


| DS4_v2 | 29 | 896 TIB | 2 PIB 


| DS5_v2 | 61 | 896 TIB | 2 PIB 


| DS13_v2 | 29 | 896 TIB | 2 PIB 


| DS14_v2 | 61 | 896 TIB | 2 PIB 


| DS15_v2 | 61 | 896 TIB | 2 PIB 


| E4s_v3 | 5 | 160 TIB | 2 PIB 


| E8s_v3 | 13 | 416 TIB | 2 PIB 


| E32s_v3 | 29 | 896 TIB | 2 PIB 


| E48s_v3 | 29 | 896 TIB | 2 PIB 


| E64is_v3 | 29 | 896 TIB | 2 PIB 


| L8s_v2 | 13 | 416 TIB | 2 PIB 


| E80ids_v4 | 61 | 896 TIB | 2 PIB 
|===


=== PARES DE HA com uma licença Premium

[cols="14,20,31,33"]
|===
| Tamanho da VM | Discos MAX Data para um par de HA | Capacidade máxima do sistema somente com discos | Capacidade máxima do sistema com discos e categorização de dados 


| DS5_v2 | 61 | 368 TIB | 368 TIB 


| DS14_v2 | 61 | 368 TIB | 368 TIB 


| DS15_v2 | 61 | 368 TIB | 368 TIB 


| E8s_v3 | 13 | 104 TIB | 368 TIB 


| E48s_v3 | 29 | 232 TIB | 368 TIB 


| E80ids_v4 | 61 | 368 TIB | 368 TIB 
|===


=== Pares DE HA com licenciamento baseado em nó

[cols="10,18,18,18,18,18"]
|===
| Tamanho da VM | Discos MAX Data para um par de HA 2+| Capacidade máxima do sistema com uma licença 2+| Capacidade máxima do sistema com várias licenças 


2+|  | *Discos sozinhos* | *Discos e categorização de dados* | *Discos sozinhos* | *Discos e categorização de dados* 


| DS4_v2 | 29 | 232 TIB | 368 TIB | 232 TIB | 2 PIB 


| DS5_v2 | 61 | 368 TIB | 368 TIB | 488 TIB | 2 PIB 


| DS13_v2 | 29 | 232 TIB | 368 TIB | 232 TIB | 2 PIB 


| DS14_v2 | 61 | 368 TIB | 368 TIB | 488 TIB | 2 PIB 


| DS15_v2 | 61 | 368 TIB | 368 TIB | 488 TIB | 2 PIB 


| E8s_v3 | 13 | 104 TIB | 368 TIB | 104 TIB | 2 PIB 


| E48s_v3 | 29 | 232 TIB | 368 TIB | 232 TIB | 2 PIB 


| E80ids_v4 | 61 | 368 TIB | 368 TIB | 488 TIB | 2 PIB 
|===


=== Pares DE HA com licenciamento baseado em capacidade

[cols="14,20,31,33"]
|===
| Tamanho da VM | Discos MAX Data para um par de HA | Capacidade máxima do sistema somente com discos | Capacidade máxima do sistema com discos e categorização de dados 


| DS4_v2 | 29 | 232 TIB | 2 PIB 


| DS5_v2 | 61 | 488 TIB | 2 PIB 


| DS13_v2 | 29 | 232 TIB | 2 PIB 


| DS14_v2 | 61 | 488 TIB | 2 PIB 


| DS15_v2 | 61 | 488 TIB | 2 PIB 


| E8s_v3 | 13 | 104 TIB | 2 PIB 


| E48s_v3 | 29 | 232 TIB | 2 PIB 


| E80ids_v4 | 61 | 488 TIB | 2 PIB 
|===


== Limites agregados

O Cloud Volumes ONTAP usa o storage Azure como discos e os agrupa em _agregados_. Agregados fornecem storage para volumes.

[cols="2*"]
|===
| Parâmetro | Limite 


| Número máximo de agregados | O mesmo que o limite do disco 


| Tamanho máximo do agregado 1 | 384 TIB de capacidade bruta para nó único 2 352 TIB de capacidade bruta para nó único com PAYGO 96 TIB de capacidade bruta para pares de HA 


| Discos por agregado | 1-12 3 


| Número máximo de grupos RAID por agregado | 1 
|===
Notas:

. O limite de capacidade agregada é baseado nos discos que compõem o agregado. O limite não inclui o storage de objetos usado para categorização de dados.
. Se estiver usando o licenciamento baseado em nós, duas licenças BYOL serão necessárias para alcançar 384 TIB.
. Todos os discos em um agregado devem ter o mesmo tamanho.




== Limites de VM de storage

Algumas configurações permitem que você crie VMs de storage adicionais (SVMs) para o Cloud Volumes ONTAP.

Estes são os limites testados. Embora teoricamente seja possível configurar VMs de armazenamento adicionais, isso não é suportado.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-azure.html["Saiba como criar VMs de armazenamento adicionais"^].

[cols="2*"]
|===
| Tipo de licença | Limite da VM de storage 


| *Freemium*  a| 
24 VMs de armazenamento total 1,2



| * Capacidade baseada em PAYGO ou BYOL* 3  a| 
24 VMs de armazenamento total 1,2



| * Baseado em nós BYOL* 4  a| 
24 VMs de armazenamento total 1,2



| *PAYGO baseado em nós*  a| 
* VM de storage de 1 U para fornecimento de dados
* VM de storage de 1 U para recuperação de desastres


|===
. Essas 24 VMs de storage podem fornecer dados ou ser configuradas para recuperação de desastres (DR).
. Cada VM de storage pode ter até três LIFs em que duas são LIFs de dados e uma é um LIF de gerenciamento de SVM.
. Para o licenciamento baseado em capacidade, não há custos adicionais de licenciamento para VMs de storage adicionais, mas há uma taxa de capacidade mínima de 4 TIB por VM de storage. Por exemplo, se você criar duas VMs de storage e cada uma tiver 2 TIB de capacidade provisionada, será cobrado um total de 8 TIB.
. Para o BYOL baseado em nós, é necessária uma licença complementar para cada VM de storage _data-service_ adicional além da primeira VM de storage fornecida com o Cloud Volumes ONTAP por padrão. Entre em Contato com sua equipe de conta para obter uma licença adicional de VM de storage.
+
As VMs de storage configuradas para recuperação de desastres (DR) não exigem uma licença complementar (elas são gratuitas), mas contam com o limite de VM de storage. Por exemplo, se você tiver 12 VMs de armazenamento de fornecimento de dados e 12 VMs de armazenamento configuradas para recuperação de desastres, atingiu o limite e não pode criar VMs de armazenamento adicionais.





== Limites de arquivo e volume

[cols="22,22,56"]
|===
| Storage lógico | Parâmetro | Limite 


.2+| *Ficheiros* | Tamanho máximo | 16 TIB 


| Máximo por volume | Depende do tamanho do volume, até 2 bilhões 


| *Volumes FlexClone* | Profundidade do clone hierárquico 2 | 499 


.3+| *Volumes FlexVol* | Máximo por nó | 500 


| Tamanho mínimo | 20 MB 


| Tamanho máximo | 100 TIB 


| *Qtrees* | Máximo por FlexVol volume | 4.995 


| *Cópias Snapshot* | Máximo por FlexVol volume | 1.023 
|===
Notas:

. O BlueXP  não oferece qualquer configuração ou suporte de orquestração para a recuperação de desastres da SVM. Ele também não dá suporte a tarefas relacionadas a storage em uma SVM adicional. Use o System Manager ou a CLI para recuperação de desastres da SVM.
+
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839856["Guia expresso de preparação para recuperação de desastres da SVM"^]
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839857["Guia do SVM Disaster Recovery Express"^]


. Profundidade de clone hierárquica é a profundidade máxima de uma hierarquia aninhada de volumes FlexClone que pode ser criada a partir de um único FlexVol volume.




== Limites de armazenamento iSCSI

[cols="3*"]
|===
| Armazenamento iSCSI | Parâmetro | Limite 


.4+| *LUNs* | Máximo por nó | 1.024 


| Número máximo de mapas LUN | 1.024 


| Tamanho máximo | 16 TIB 


| Máximo por volume | 512 


| *grupos* | Máximo por nó | 256 


.2+| *Iniciadores* | Máximo por nó | 512 


| Máximo por grupo | 128 


| * Sessões iSCSI* | Máximo por nó | 1.024 


.2+| *LIFs* | Máximo por porta | 32 


| Máximo por portset | 32 


| *Portsets* | Máximo por nó | 256 
|===